import React, { createContext, useState, useContext } from "react";

const ItemsContext = createContext();

const itemsList = [
  {
    title: "خدمة العناية بالشعر الكيرلي",
    descreption: "توفر هذه الخدمة العناية بالشعر الكيرلي",
    provider: "سارة الثقفي",
    price: "120",
    category: "العناية بالشعر",
    image: require("../assets/wellaproblogcurlyhaircareimage1.jpg"),
    rating: 4,
    liked: false,
    type: "provider",
  },
  {
    title: "خدمة العناية بالشعر",
    descreption: "توفر هذه الخدمة العناية بالشعر",
    provider: "مركز روفانا",
    price: "120",
    category: "العناية بالشعر",
    image: require("../assets/IMG_20240501_175723_573.jpg"),
    rating: 4,
    liked: false,
    type: "shop",
  },
  {
    title: "خدمة استشوار الشعر",
    descreption: "توفر هذه الخدمة استشوار الشعر",
    provider: "خديجة عامر",
    offer: "10%",
    price: "60",
    category: "الاستشوار",
    image: require("../assets/Blow-Dry-.jpg"),
    rating: 3,
    liked: false,
    type: "provider",
  },
  {
    title: "خدمة قص الشعر",
    descreption: "توفر هذه الخدمة قص الشعر",
    provider: "أميرة القحطاني",
    price: "90",
    category: "قص الشعر",
    image: require("../assets/image-80.png"),
    rating: 3,
    liked: false,

    type: "provider",
  },
  {
    title: "خدمة إزالة الشعر",
    descreption: "توفر هذه الخدمة إزالة شعر الجسم بالشمع",
    provider: "أريج العتيبي",
    price: "130",
    offer: "25%",
    category: "إزالة الشعر",
    image: require("../assets/hair-de2fe0f99.jpg"),
    rating: 4,
    liked: false,

    type: "provider",
  },
  {
    title: "خدمة العناية بالشعر الطويل",
    descreption: "توفر هذه الخدمة العناية بالشعر الطويل",
    provider: "فاطمة الطويل",
    price: "210",
    offer: "30%",
    category: "العناية بالشعر",
    image: require("../assets/hair-growth.jpg"),
    rating: 4,
    liked: false,
    type: "provider",
  },
  {
    title: "خدمة استشوار الشعر الكيرلي",
    descreption: "توفر هذه الخدمة استشوار الشعر الكيرلي",
    provider: "خديجة عامر",
    price: "100",
    category: "الاستشوار",
    image: require("../assets/intro-1663610670.jpg"),
    rating: 4,
    liked: false,
    type: "provider",
  },
  {
    title: "خدمة قص الشعر",
    descreption: "توفر هذه الخدمة قص الشعر",
    provider: "سارة الثقفي",
    price: "50",
    category: "قص الشعر",
    image: require("../assets/ddc38ec4d9b3b0815115364a7367d444.jpg"),
    rating: 2,
    liked: false,
    type: "provider",
  },
  {
    title: "خدمة قص الشعر",
    descreption: "توفر هذه الخدمة قص الشعر",
    provider: "مركز روفانا",
    price: "50",
    category: "قص الشعر",
    image: require("../assets/IMG_20240501_175723_573.jpg"),
    rating: 2,
    liked: false,
    type: "shop",
  },
  {
    title: "خدمة الواكس البرازيلي",
    descreption: "توفر هذه الخدمة إزالة شعر الجسم بالشمع",
    provider: "أريج العتيبي",
    price: "200",
    category: "إزالة الشعر",
    image: require("../assets/GettyImagdc84630e.jpg"),
    rating: 5,
    liked: false,
    type: "provider",
  },
  {
    title: "خدمة العناية بالشعر",
    descreption: "توفر هذه الخدمة العناية بالشعر",
    provider: "ريم صالح",
    price: "180",
    category: "العناية بالشعر",
    image: require("../assets/01_Haircare_.jpg"),
    rating: 3,
    liked: false,
    type: "provider",
  },
  {
    title: "خدمة إزالة الشعر بالليزر",
    descreption: "توفر هذه الخدمة إزالة شعر الجسم بالليزر",
    provider: "حورية سطام",
    price: "310",
    category: "إزالة الشعر",
    image: require("../assets/images.jpeg"),
    rating: 5,
    liked: false,
    type: "provider",
  },
  {
    title: "حمام شعر",
    descreption: "توفر هذه الخدمة حمام شعر",
    provider: "لطيفة الغامدي",
    price: "80",
    offer: "10%",
    category: "العناية بالشعر",
    image: require("../assets/example.jpeg"),
    rating: 2,
    liked: false,
    type: "provider",
  },
  {
    title: "خدمة العناية بالبشرة",
    descreption: "تقدم هذه الخدمة العناية بالبشرة",
    provider: "مركز يوريكا",
    price: "200",
    offer: "10%",
    image: require("../assets/IMG_20240501_175723_258.jpg"),
    category: "العناية بالجسم",
    rating: 5,
    liked: false,
    type: "shop",
  },
  {
    title: "خدمة ازالة الشعر بالليزر",
    descreption: "تقدم هذه الخدمة إزالة الشعر بالليزر",
    provider: "مركز سيدتي",
    price: "110",
    offer: "30%",
    image: require("../assets/IMG_20240501_175723_849.jpg"),
    category: "العناية بالجسم",
    rating: 5,
    liked: true,
    type: "shop",
  },
];

export const ItemsProvider = ({ children }) => {
  const [items, setItems] = useState([...itemsList]);

  return (
    <ItemsContext.Provider value={{ items, setItems }}>
      {children}
    </ItemsContext.Provider>
  );
};

export const useItems = () => useContext(ItemsContext);
